#ejecutable: factorial.o
#	gcc factorial.o -o ejecutable
factorialassembly: factorialassembly.o
	gcc factorialassembly.o -o factorialassembly
factorialassembly.o: factorialassembly.asm
	nasm -f elf factorialassembly.asm	

